services:

  web:
    build: ./web
    container_name: student-web
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - app

  app:
    build: ./app
    container_name: student-app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    networks:
      - webnet
      - dbnet
    depends_on:
      - db

  db:
    build: ./db
    container_name: student-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dbnet

volumes:
  mysql_data:

networks:
  webnet:
  dbnet:
